# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  name: 
    description: 'File name'
    required: true
runs:
  using: node12
  main: dist/index.js
  post: dist/index.js